# permissions for end users to view cryptoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crypto-viewer-role
rules:
- apiGroups:
  - devops.dxas90
  resources:
  - cryptoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.dxas90
  resources:
  - cryptoes/status
  verbs:
  - get
