# permissions for end users to edit cryptoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crypto-editor-role
rules:
- apiGroups:
  - devops.dxas90
  resources:
  - cryptoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.dxas90
  resources:
  - cryptoes/status
  verbs:
  - get
