# permissions for end users to edit statuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: status-editor-role
rules:
- apiGroups:
  - devops.dxas90
  resources:
  - statuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.dxas90
  resources:
  - statuses/status
  verbs:
  - get
