# permissions for end users to view statuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: status-viewer-role
rules:
- apiGroups:
  - devops.dxas90
  resources:
  - statuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.dxas90
  resources:
  - statuses/status
  verbs:
  - get
