---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-bobr-status
  labels:
    app: k8s-bobr-status
subjects:
  - kind: ServiceAccount
    name: k8s-bobr-status
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-bobr-status-role
